name: nutsnbolts
description: "Mobile app for you to get help with everyday maintenance tasks in your home"
publish_to: "none"
version: 0.3.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^1.3.3
  cloud_firestore: ^5.0.2
  dart_openai: ^5.1.0
  dash_chat_2: ^0.0.21
  dropdown_button2: ^2.3.9
  envied: ^0.5.4+1
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  firebase_ui_auth: ^1.15.0
  firebase_ui_oauth_google: ^1.3.3
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.0.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  loading_animation_widget: ^1.2.1
  location: ^7.0.0
  path: ^1.9.0
  provider: ^6.1.2
  swipe_cards: ^2.0.0+1
  multi_select_flutter: ^4.1.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true

  assets:
    - assets/nnb.jpeg
    - assets/images/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 400
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 400
